version: "3"
services:
  client:
    build:
      context:
        ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/:/client
      - /client/node_modules
    networks:
      - app-network
  server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server/:/src/app/server
      - /server/node_modules
    networks:
      - app-network
networks: 
  app-network: